from typing import Any, Dict

from langchain.callbacks.base import BaseCallbackHandler

from ..tools.cache_tools import CacheTools
from .cache.cache_handler import CacheHandler


class ToolsHandler(BaseCallbackHandler):
    """Callback handler for tool usage."""

    last_used_tool: Dict[str, Any] = {}
    cache: CacheHandler = None

    def __init__(self, cache: CacheHandler = None, **kwargs: Any):

        """
        Initialize the callback handler.

        Args:
            cache (CacheHandler, optional): The cache handler. Defaults to None.
            **kwargs (Any): Additional keyword arguments.

        Raises:
            <ExceptionType>: <Description of the exception raised>

        """
        self.cache = cache
        super().__init__(**kwargs)

    def on_tool_start(
        self, serialized: Dict[str, Any], input_str: str, **kwargs: Any
    ) -> Any:
        
        """        Run when tool starts running.

            Args:
                serialized (Dict[str, Any]): Serialized data.
                input_str (str): Input string.
                **kwargs (Any): Additional keyword arguments.

            Raises:
                (Exception): If the 'name' is not in the list ["invalid_tool", "_Exception"].

            Returns:
                Any: The result of the function.
        """
        name = serialized.get("name")
        if name not in ["invalid_tool", "_Exception"]:
            tools_usage = {
                "tool": name,
                "input": input_str,
            }
            self.last_used_tool = tools_usage

    def on_tool_end(self, output: str, **kwargs: Any) -> Any:
        
        """        Run when tool ends running.

            Args:
                output (str): The output generated by the tool.
                **kwargs (Any): Additional keyword arguments.

            Raises:
                (SomeException): This function may raise SomeException under certain conditions.

            Returns:
                Any: The return value of the function.
        """
        if (
            "is not a valid tool" not in output
            and "Invalid or incomplete response" not in output
            and "Invalid Format" not in output
        ):
            if self.last_used_tool["tool"] != CacheTools().name:
                self.cache.add(
                    tool=self.last_used_tool["tool"],
                    input=self.last_used_tool["input"],
                    output=output,
                )
